# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import pay_pal_checkout_python_sdk
from pay_pal_checkout_python_sdk.paths.v2_checkout_orders_id_trackers_tracker_id import patch
from pay_pal_checkout_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestV2CheckoutOrdersIdTrackersTrackerId(ApiTestMixin, unittest.TestCase):
    """
    V2CheckoutOrdersIdTrackersTrackerId unit test stubs
        Update or cancel tracking information for a PayPal order
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
