# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.money import Money

class RequiredAmountBreakdown(TypedDict):
    pass

class OptionalAmountBreakdown(TypedDict, total=False):
    item_total: Money

    shipping: Money

    handling: Money

    tax_total: Money

    insurance: Money

    shipping_discount: Money

    discount: Money

class AmountBreakdown(RequiredAmountBreakdown, OptionalAmountBreakdown):
    pass
