# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredApplePayPaymentData(TypedDict):
    pass

class OptionalApplePayPaymentData(TypedDict, total=False):
    # Online payment cryptogram, as defined by 3D Secure. The pattern is defined by an external party and supports Unicode.
    cryptogram: str

    # ECI indicator, as defined by 3- Secure. The pattern is defined by an external party and supports Unicode.
    eci_indicator: str

    # Encoded Apple Pay EMV Payment Structure used for payments in China. The pattern is defined by an external party and supports Unicode.
    emv_data: str

    # Bank Key encrypted Apple Pay PIN. The pattern is defined by an external party and supports Unicode.
    pin: str

class ApplePayPaymentData(RequiredApplePayPaymentData, OptionalApplePayPaymentData):
    pass
