# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.card import Card
from pay_pal_checkout_python_sdk.type.card_experience_context import CardExperienceContext
from pay_pal_checkout_python_sdk.type.card_stored_credential import CardStoredCredential
from pay_pal_checkout_python_sdk.type.network_token_request import NetworkTokenRequest
from pay_pal_checkout_python_sdk.type.vault_id import VaultId

CardRequest = typing.Union[Card,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
CardRequest = object
