# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.level2_card_processing_data import Level2CardProcessingData
from pay_pal_checkout_python_sdk.type.level3_card_processing_data import Level3CardProcessingData

class RequiredCardSupplementaryData(TypedDict):
    pass

class OptionalCardSupplementaryData(TypedDict, total=False):
    level_2: Level2CardProcessingData

    level_3: Level3CardProcessingData

class CardSupplementaryData(RequiredCardSupplementaryData, OptionalCardSupplementaryData):
    pass
