# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.customer import Customer
from pay_pal_checkout_python_sdk.type.vault_instruction_base import VaultInstructionBase

class RequiredCardAttributes(TypedDict):
    pass

class OptionalCardAttributes(TypedDict, total=False):
    customer: Customer

    vault: VaultInstructionBase

class CardAttributes(RequiredCardAttributes, OptionalCardAttributes):
    pass
