# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.cobranded_card_labels import CobrandedCardLabels
from pay_pal_checkout_python_sdk.type.money import Money
from pay_pal_checkout_python_sdk.type.payee_base import PayeeBase

class RequiredCobrandedCard(TypedDict):
    pass

class OptionalCobrandedCard(TypedDict, total=False):
    labels: CobrandedCardLabels

    payee: PayeeBase

    amount: Money

class CobrandedCard(RequiredCobrandedCard, OptionalCobrandedCard):
    pass
