# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.error_location import ErrorLocation

class RequiredErrorDetails(TypedDict):
    # The unique, fine-grained application-level error code.
    issue: str

class OptionalErrorDetails(TypedDict, total=False):
    # The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value.
    description: str

    # The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors.
    field: str

    # The value of the field that caused the error.
    value: str

    location: ErrorLocation

class ErrorDetails(RequiredErrorDetails, OptionalErrorDetails):
    pass
