# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.money import Money

class RequiredItem(TypedDict):
    # The item name or title.
    name: str

    unit_amount: Money

    # The item quantity. Must be a whole number.
    quantity: str

class OptionalItem(TypedDict, total=False):
    # The detailed item description.
    description: str

    tax: Money

    # The stock keeping unit (SKU) for the item.
    sku: str

    # The item category type.
    category: str

class Item(RequiredItem, OptionalItem):
    pass
