# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredName(TypedDict):
    pass

class OptionalName(TypedDict, total=False):
    # The prefix, or title, to the party's name.
    prefix: str

    # When the party is a person, the party's given, or first, name.
    given_name: str

    # When the party is a person, the party's surname or family name. Also known as the last name. Required when the party is a person. Use also to store multiple surnames including the matronymic, or mother's, surname.
    surname: str

    # When the party is a person, the party's middle name. Use also to store multiple middle names including the patronymic, or father's, middle name.
    middle_name: str

    # The suffix for the party's name.
    suffix: str

    # DEPRECATED. The party's alternate name. Can be a business name, nickname, or any other name that cannot be split into first, last name. Required when the party is a business.
    alternate_full_name: str

    # When the party is a person, the party's full name.
    full_name: str

class Name(RequiredName, OptionalName):
    pass
