# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.country_code import CountryCode
from pay_pal_checkout_python_sdk.type.email_address import EmailAddress
from pay_pal_checkout_python_sdk.type.full_name import FullName

class RequiredP24(TypedDict):
    pass

class OptionalP24(TypedDict, total=False):
    name: FullName

    email: EmailAddress

    country_code: CountryCode

    # P24 generated payment description.
    payment_descriptor: str

    # Numeric identifier of the payment scheme or bank used for the payment.
    method_id: str

    # Friendly name of the payment scheme or bank used for the payment.
    method_description: str

class P24(RequiredP24, OptionalP24):
    pass
