# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.address_portable import AddressPortable
from pay_pal_checkout_python_sdk.type.date_no_time import DateNoTime
from pay_pal_checkout_python_sdk.type.name import Name
from pay_pal_checkout_python_sdk.type.payer_base import PayerBase
from pay_pal_checkout_python_sdk.type.phone_with_type import PhoneWithType
from pay_pal_checkout_python_sdk.type.tax_info import TaxInfo

Payer = typing.Union[PayerBase,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
Payer = object
