# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.apple_pay_request import ApplePayRequest
from pay_pal_checkout_python_sdk.type.bancontact_request import BancontactRequest
from pay_pal_checkout_python_sdk.type.blik_request import BlikRequest
from pay_pal_checkout_python_sdk.type.card_request import CardRequest
from pay_pal_checkout_python_sdk.type.eps_request import EpsRequest
from pay_pal_checkout_python_sdk.type.giropay_request import GiropayRequest
from pay_pal_checkout_python_sdk.type.ideal_request import IdealRequest
from pay_pal_checkout_python_sdk.type.mybank_request import MybankRequest
from pay_pal_checkout_python_sdk.type.p24_request import P24Request
from pay_pal_checkout_python_sdk.type.paypal_wallet import PaypalWallet
from pay_pal_checkout_python_sdk.type.sofort_request import SofortRequest
from pay_pal_checkout_python_sdk.type.token import Token
from pay_pal_checkout_python_sdk.type.trustly_request import TrustlyRequest
from pay_pal_checkout_python_sdk.type.venmo_wallet_request import VenmoWalletRequest

class RequiredPaymentSource(TypedDict):
    pass

class OptionalPaymentSource(TypedDict, total=False):
    card: CardRequest

    token: Token

    paypal: PaypalWallet

    bancontact: BancontactRequest

    blik: BlikRequest

    eps: EpsRequest

    giropay: GiropayRequest

    ideal: IdealRequest

    mybank: MybankRequest

    p24: P24Request

    sofort: SofortRequest

    trustly: TrustlyRequest

    apple_pay: ApplePayRequest

    google_pay: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

    venmo: VenmoWalletRequest

class PaymentSource(RequiredPaymentSource, OptionalPaymentSource):
    pass
