# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.authorization_with_additional_data import AuthorizationWithAdditionalData
from pay_pal_checkout_python_sdk.type.capture import Capture
from pay_pal_checkout_python_sdk.type.refund import Refund

class RequiredPaymentCollection(TypedDict):
    pass

class OptionalPaymentCollection(TypedDict, total=False):
    # An array of authorized payments for a purchase unit. A purchase unit can have zero or more authorized payments.
    authorizations: typing.List[AuthorizationWithAdditionalData]

    # An array of captured payments for a purchase unit. A purchase unit can have zero or more captured payments.
    captures: typing.List[Capture]

    # An array of refunds for a purchase unit. A purchase unit can have zero or more refunds.
    refunds: typing.List[Refund]

class PaymentCollection(RequiredPaymentCollection, OptionalPaymentCollection):
    pass
