# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.account_id2 import AccountId2
from pay_pal_checkout_python_sdk.type.address_portable2 import AddressPortable2
from pay_pal_checkout_python_sdk.type.date_no_time import DateNoTime
from pay_pal_checkout_python_sdk.type.email import Email
from pay_pal_checkout_python_sdk.type.name2 import Name2
from pay_pal_checkout_python_sdk.type.paypal_wallet_attributes_response import PaypalWalletAttributesResponse
from pay_pal_checkout_python_sdk.type.phone2 import Phone2
from pay_pal_checkout_python_sdk.type.phone_type2 import PhoneType2
from pay_pal_checkout_python_sdk.type.tax_info import TaxInfo

class RequiredPaypalWalletResponse(TypedDict):
    pass

class OptionalPaypalWalletResponse(TypedDict, total=False):
    email_address: Email

    account_id: AccountId2

    # The account status indicates whether the buyer has verified the financial details associated with their PayPal account.
    account_status: str

    name: Name2

    phone_type: PhoneType2

    phone_number: Phone2

    birth_date: DateNoTime

    tax_info: TaxInfo

    address: AddressPortable2

    attributes: PaypalWalletAttributesResponse

class PaypalWalletResponse(RequiredPaypalWalletResponse, OptionalPaypalWalletResponse):
    pass
