# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.cobranded_card import CobrandedCard
from pay_pal_checkout_python_sdk.type.paypal_wallet_vault_response import PaypalWalletVaultResponse

class RequiredPaypalWalletAttributesResponse(TypedDict):
    pass

class OptionalPaypalWalletAttributesResponse(TypedDict, total=False):
    vault: PaypalWalletVaultResponse

    # An array of merchant cobranded cards used by buyer to complete an order. This array will be present if a merchant has onboarded their cobranded card with PayPal and provided corresponding label(s).
    cobranded_cards: typing.List[CobrandedCard]

class PaypalWalletAttributesResponse(RequiredPaypalWalletAttributesResponse, OptionalPaypalWalletAttributesResponse):
    pass
