# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.activity_timestamps import ActivityTimestamps
from pay_pal_checkout_python_sdk.type.link_description import LinkDescription
from pay_pal_checkout_python_sdk.type.money import Money
from pay_pal_checkout_python_sdk.type.net_amount_breakdown_item import NetAmountBreakdownItem
from pay_pal_checkout_python_sdk.type.payee_base import PayeeBase
from pay_pal_checkout_python_sdk.type.platform_fee import PlatformFee
from pay_pal_checkout_python_sdk.type.refund_status import RefundStatus

Refund = typing.Union[RefundStatus,typing.Union[bool, date, datetime, dict, float, int, list, str, None],ActivityTimestamps]
Refund = object
