# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.seller_protection_dispute_categories import SellerProtectionDisputeCategories

class RequiredSellerProtection(TypedDict):
    pass

class OptionalSellerProtection(TypedDict, total=False):
    # Indicates whether the transaction is eligible for seller protection. For information, see [PayPal Seller Protection for Merchants](https://www.paypal.com/us/webapps/mpp/security/seller-protection).
    status: str

    dispute_categories: SellerProtectionDisputeCategories

class SellerProtection(RequiredSellerProtection, OptionalSellerProtection):
    pass
