# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTaxInfo(TypedDict):
    # The customer's tax ID value.
    tax_id: str

    # The customer's tax ID type.
    tax_id_type: str

class OptionalTaxInfo(TypedDict, total=False):
    pass

class TaxInfo(RequiredTaxInfo, OptionalTaxInfo):
    pass
