# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredTrackerItem(TypedDict):
    pass

class OptionalTrackerItem(TypedDict, total=False):
    # The item name or title.
    name: str

    # The item quantity. Must be a whole number.
    quantity: str

    # The stock keeping unit (SKU) for the item. This can contain unicode characters.
    sku: str

    # The URL to the item being purchased. Visible to buyer and used in buyer experiences.
    url: str

    # The URL of the item's image. File type and size restrictions apply. An image that violates these restrictions will not be honored.
    image_url: str

    upc: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class TrackerItem(RequiredTrackerItem, OptionalTrackerItem):
    pass
