# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredVenmoWalletExperienceContext(TypedDict):
    pass

class OptionalVenmoWalletExperienceContext(TypedDict, total=False):
    # The business name of the merchant. The pattern is defined by an external party and supports Unicode.
    brand_name: str

    # The location from which the shipping address is derived.
    shipping_preference: str

class VenmoWalletExperienceContext(RequiredVenmoWalletExperienceContext, OptionalVenmoWalletExperienceContext):
    pass
