# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.account_id2 import AccountId2
from pay_pal_checkout_python_sdk.type.address_portable2 import AddressPortable2
from pay_pal_checkout_python_sdk.type.email import Email
from pay_pal_checkout_python_sdk.type.name2 import Name2
from pay_pal_checkout_python_sdk.type.phone2 import Phone2
from pay_pal_checkout_python_sdk.type.venmo_wallet_attributes_response import VenmoWalletAttributesResponse

class RequiredVenmoWalletResponse(TypedDict):
    pass

class OptionalVenmoWalletResponse(TypedDict, total=False):
    email_address: Email

    account_id: AccountId2

    # The Venmo user name chosen by the user, also know as a Venmo handle.
    user_name: str

    name: Name2

    phone_number: Phone2

    address: AddressPortable2

    attributes: VenmoWalletAttributesResponse

class VenmoWalletResponse(RequiredVenmoWalletResponse, OptionalVenmoWalletResponse):
    pass
