# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from pay_pal_checkout_python_sdk.type.customer import Customer
from pay_pal_checkout_python_sdk.type.vault_venmo_wallet_base import VaultVenmoWalletBase

class RequiredVenmoWalletAttributes(TypedDict):
    pass

class OptionalVenmoWalletAttributes(TypedDict, total=False):
    customer: Customer

    vault: VaultVenmoWalletBase

class VenmoWalletAttributes(RequiredVenmoWalletAttributes, OptionalVenmoWalletAttributes):
    pass
