# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class IdealRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Information needed to pay using iDEAL.
    """


    class MetaOapg:
        required = {
            "country_code",
            "name",
        }
        
        class properties:
        
            @staticmethod
            def name() -> typing.Type['FullName']:
                return FullName
        
            @staticmethod
            def country_code() -> typing.Type['CountryCode']:
                return CountryCode
        
            @staticmethod
            def bic() -> typing.Type['Bic']:
                return Bic
        
            @staticmethod
            def experience_context() -> typing.Type['ExperienceContextBase']:
                return ExperienceContextBase
            attributes = schemas.AnyTypeSchema
            __annotations__ = {
                "name": name,
                "country_code": country_code,
                "bic": bic,
                "experience_context": experience_context,
                "attributes": attributes,
            }
    
    country_code: 'CountryCode'
    name: 'FullName'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> 'FullName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["country_code"]) -> 'CountryCode': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bic"]) -> 'Bic': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["experience_context"]) -> 'ExperienceContextBase': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> MetaOapg.properties.attributes: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "country_code", "bic", "experience_context", "attributes", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> 'FullName': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["country_code"]) -> 'CountryCode': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bic"]) -> typing.Union['Bic', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["experience_context"]) -> typing.Union['ExperienceContextBase', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> typing.Union[MetaOapg.properties.attributes, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "country_code", "bic", "experience_context", "attributes", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        country_code: 'CountryCode',
        name: 'FullName',
        bic: typing.Union['Bic', schemas.Unset] = schemas.unset,
        experience_context: typing.Union['ExperienceContextBase', schemas.Unset] = schemas.unset,
        attributes: typing.Union[MetaOapg.properties.attributes, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IdealRequest':
        return super().__new__(
            cls,
            *args,
            country_code=country_code,
            name=name,
            bic=bic,
            experience_context=experience_context,
            attributes=attributes,
            _configuration=_configuration,
            **kwargs,
        )

from pay_pal_checkout_python_sdk.model.bic import Bic
from pay_pal_checkout_python_sdk.model.country_code import CountryCode
from pay_pal_checkout_python_sdk.model.experience_context_base import ExperienceContextBase
from pay_pal_checkout_python_sdk.model.full_name import FullName
