# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class ParesStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Transactions status result identifier. The outcome of the issuer's authentication.
    """
    
    @schemas.classproperty
    def Y(cls):
        return cls("Y")
    
    @schemas.classproperty
    def N(cls):
        return cls("N")
    
    @schemas.classproperty
    def U(cls):
        return cls("U")
    
    @schemas.classproperty
    def A(cls):
        return cls("A")
    
    @schemas.classproperty
    def C(cls):
        return cls("C")
    
    @schemas.classproperty
    def R(cls):
        return cls("R")
    
    @schemas.classproperty
    def D(cls):
        return cls("D")
    
    @schemas.classproperty
    def I(cls):
        return cls("I")
