# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class PatchRequest(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    An array of JSON patch objects to apply partial updates to resources.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['Patch']:
            return Patch

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['Patch'], typing.List['Patch']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'PatchRequest':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'Patch':
        return super().__getitem__(i)

from pay_pal_checkout_python_sdk.model.patch import Patch
