# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class PaymentMethod(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The customer and merchant payment preferences.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def payee_preferred() -> typing.Type['PayeePaymentMethodPreference']:
                return PayeePaymentMethodPreference
            
            
            class standard_entry_class_code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def TEL(cls):
                    return cls("TEL")
                
                @schemas.classproperty
                def WEB(cls):
                    return cls("WEB")
                
                @schemas.classproperty
                def CCD(cls):
                    return cls("CCD")
                
                @schemas.classproperty
                def PPD(cls):
                    return cls("PPD")
            __annotations__ = {
                "payee_preferred": payee_preferred,
                "standard_entry_class_code": standard_entry_class_code,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["payee_preferred"]) -> 'PayeePaymentMethodPreference': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["standard_entry_class_code"]) -> MetaOapg.properties.standard_entry_class_code: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["payee_preferred", "standard_entry_class_code", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["payee_preferred"]) -> typing.Union['PayeePaymentMethodPreference', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["standard_entry_class_code"]) -> typing.Union[MetaOapg.properties.standard_entry_class_code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["payee_preferred", "standard_entry_class_code", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        payee_preferred: typing.Union['PayeePaymentMethodPreference', schemas.Unset] = schemas.unset,
        standard_entry_class_code: typing.Union[MetaOapg.properties.standard_entry_class_code, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PaymentMethod':
        return super().__new__(
            cls,
            *args,
            payee_preferred=payee_preferred,
            standard_entry_class_code=standard_entry_class_code,
            _configuration=_configuration,
            **kwargs,
        )

from pay_pal_checkout_python_sdk.model.payee_payment_method_preference import PayeePaymentMethodPreference
