# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class ShipmentTrackingStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The status of the item shipment. For allowed values, see <a href="/docs/tracking/reference/shipping-status/">Shipping Statuses</a>.
    """
    
    @schemas.classproperty
    def CANCELLED(cls):
        return cls("CANCELLED")
    
    @schemas.classproperty
    def DELIVERED(cls):
        return cls("DELIVERED")
    
    @schemas.classproperty
    def LOCAL_PICKUP(cls):
        return cls("LOCAL_PICKUP")
    
    @schemas.classproperty
    def ON_HOLD(cls):
        return cls("ON_HOLD")
    
    @schemas.classproperty
    def SHIPPED(cls):
        return cls("SHIPPED")
    
    @schemas.classproperty
    def SHIPMENT_CREATED(cls):
        return cls("SHIPMENT_CREATED")
    
    @schemas.classproperty
    def DROPPED_OFF(cls):
        return cls("DROPPED_OFF")
    
    @schemas.classproperty
    def IN_TRANSIT(cls):
        return cls("IN_TRANSIT")
    
    @schemas.classproperty
    def RETURNED(cls):
        return cls("RETURNED")
    
    @schemas.classproperty
    def LABEL_PRINTED(cls):
        return cls("LABEL_PRINTED")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("ERROR")
    
    @schemas.classproperty
    def UNCONFIRMED(cls):
        return cls("UNCONFIRMED")
    
    @schemas.classproperty
    def PICKUP_FAILED(cls):
        return cls("PICKUP_FAILED")
    
    @schemas.classproperty
    def DELIVERY_DELAYED(cls):
        return cls("DELIVERY_DELAYED")
    
    @schemas.classproperty
    def DELIVERY_SCHEDULED(cls):
        return cls("DELIVERY_SCHEDULED")
    
    @schemas.classproperty
    def DELIVERY_FAILED(cls):
        return cls("DELIVERY_FAILED")
    
    @schemas.classproperty
    def INRETURN(cls):
        return cls("INRETURN")
    
    @schemas.classproperty
    def IN_PROCESS(cls):
        return cls("IN_PROCESS")
    
    @schemas.classproperty
    def NEW(cls):
        return cls("NEW")
    
    @schemas.classproperty
    def VOID(cls):
        return cls("VOID")
    
    @schemas.classproperty
    def PROCESSED(cls):
        return cls("PROCESSED")
    
    @schemas.classproperty
    def NOT_SHIPPED(cls):
        return cls("NOT_SHIPPED")
    
    @schemas.classproperty
    def COMPLETED(cls):
        return cls("COMPLETED")
