# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class V3VaultInstructionBase(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Base vaulting specification. The object can be extended for specific use cases within each payment_source that supports vaulting.
    """


    class MetaOapg:
        required = {
            "store_in_vault",
        }
        
        class properties:
        
            @staticmethod
            def store_in_vault() -> typing.Type['StoreInVaultInstruction']:
                return StoreInVaultInstruction
            __annotations__ = {
                "store_in_vault": store_in_vault,
            }
    
    store_in_vault: 'StoreInVaultInstruction'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["store_in_vault"]) -> 'StoreInVaultInstruction': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["store_in_vault", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["store_in_vault"]) -> 'StoreInVaultInstruction': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["store_in_vault", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        store_in_vault: 'StoreInVaultInstruction',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'V3VaultInstructionBase':
        return super().__new__(
            cls,
            *args,
            store_in_vault=store_in_vault,
            _configuration=_configuration,
            **kwargs,
        )

from pay_pal_checkout_python_sdk.model.store_in_vault_instruction import StoreInVaultInstruction
