# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401


class VenmoWalletExperienceContext(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Customizes the buyer experience during the approval process for payment with Venmo.<blockquote><strong>Note:</strong> Partners and Marketplaces might configure <code>shipping_preference</code> during partner account setup, which overrides the request values.</blockquote>
    """


    class MetaOapg:
        
        class properties:
            
            
            class brand_name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 127
                    min_length = 1
                    regex=[{
                        'pattern': r'^.*$',
                    }]
            
            
            class shipping_preference(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 24
                    min_length = 1
                    regex=[{
                        'pattern': r'^[A-Z_]+$',
                    }]
                    enum_value_to_name = {
                        "GET_FROM_FILE": "GET_FROM_FILE",
                        "NO_SHIPPING": "NO_SHIPPING",
                        "SET_PROVIDED_ADDRESS": "SET_PROVIDED_ADDRESS",
                    }
                
                @schemas.classproperty
                def GET_FROM_FILE(cls):
                    return cls("GET_FROM_FILE")
                
                @schemas.classproperty
                def NO_SHIPPING(cls):
                    return cls("NO_SHIPPING")
                
                @schemas.classproperty
                def SET_PROVIDED_ADDRESS(cls):
                    return cls("SET_PROVIDED_ADDRESS")
            __annotations__ = {
                "brand_name": brand_name,
                "shipping_preference": shipping_preference,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["brand_name"]) -> MetaOapg.properties.brand_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shipping_preference"]) -> MetaOapg.properties.shipping_preference: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["brand_name", "shipping_preference", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["brand_name"]) -> typing.Union[MetaOapg.properties.brand_name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shipping_preference"]) -> typing.Union[MetaOapg.properties.shipping_preference, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["brand_name", "shipping_preference", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        brand_name: typing.Union[MetaOapg.properties.brand_name, str, schemas.Unset] = schemas.unset,
        shipping_preference: typing.Union[MetaOapg.properties.shipping_preference, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'VenmoWalletExperienceContext':
        return super().__new__(
            cls,
            *args,
            brand_name=brand_name,
            shipping_preference=shipping_preference,
            _configuration=_configuration,
            **kwargs,
        )
