# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

import unittest

import pay_pal_checkout_python_sdk
from pay_pal_checkout_python_sdk.model.vault_instruction_base import VaultInstructionBase
from pay_pal_checkout_python_sdk import configuration


class TestVaultInstructionBase(unittest.TestCase):
    """VaultInstructionBase unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
