# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

import unittest

import pay_pal_checkout_python_sdk
from pay_pal_checkout_python_sdk.model.level2_card_processing_data import Level2CardProcessingData
from pay_pal_checkout_python_sdk import configuration


class TestLevel2CardProcessingData(unittest.TestCase):
    """Level2CardProcessingData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
