# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from pay_pal_checkout_python_sdk.paths.v2_checkout_orders_id_trackers_tracker_id.patch import UpdateTrackingInfo
from pay_pal_checkout_python_sdk.apis.tags.trackers_api_raw import TrackersApiRaw


class TrackersApi(
    UpdateTrackingInfo,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TrackersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TrackersApiRaw(api_client)
