# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.money import Money

class AmountBreakdown(BaseModel):
    item_total: typing.Optional[Money] = Field(None, alias='item_total')

    shipping: typing.Optional[Money] = Field(None, alias='shipping')

    handling: typing.Optional[Money] = Field(None, alias='handling')

    tax_total: typing.Optional[Money] = Field(None, alias='tax_total')

    insurance: typing.Optional[Money] = Field(None, alias='insurance')

    shipping_discount: typing.Optional[Money] = Field(None, alias='shipping_discount')

    discount: typing.Optional[Money] = Field(None, alias='discount')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
