# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.blik_one_click_response import BlikOneClickResponse
from pay_pal_checkout_python_sdk.pydantic.country_code import CountryCode
from pay_pal_checkout_python_sdk.pydantic.email_address import EmailAddress
from pay_pal_checkout_python_sdk.pydantic.full_name import FullName

class Blik(BaseModel):
    name: typing.Optional[FullName] = Field(None, alias='name')

    country_code: typing.Optional[CountryCode] = Field(None, alias='country_code')

    email: typing.Optional[EmailAddress] = Field(None, alias='email')

    one_click: typing.Optional[BlikOneClickResponse] = Field(None, alias='one_click')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
