# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.blik_experience_context import BlikExperienceContext
from pay_pal_checkout_python_sdk.pydantic.blik_one_click import BlikOneClick
from pay_pal_checkout_python_sdk.pydantic.blik_seamless import BlikSeamless
from pay_pal_checkout_python_sdk.pydantic.country_code import CountryCode
from pay_pal_checkout_python_sdk.pydantic.email_address import EmailAddress
from pay_pal_checkout_python_sdk.pydantic.full_name import FullName

class BlikRequest(BaseModel):
    name: FullName = Field(alias='name')

    country_code: CountryCode = Field(alias='country_code')

    email: typing.Optional[EmailAddress] = Field(None, alias='email')

    experience_context: typing.Optional[BlikExperienceContext] = Field(None, alias='experience_context')

    level_0: typing.Optional[BlikSeamless] = Field(None, alias='level_0')

    one_click: typing.Optional[BlikOneClick] = Field(None, alias='one_click')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
