# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class BlikOneClick(BaseModel):
    # The merchant generated, unique reference serving as a primary identifier for accounts connected between Blik and a merchant.
    consumer_reference: str = Field(alias='consumer_reference')

    # The 6-digit code used to authenticate a consumer within BLIK.
    auth_code: typing.Optional[str] = Field(None, alias='auth_code')

    # A bank defined identifier used as a display name to allow the payer to differentiate between multiple registered bank accounts.
    alias_label: typing.Optional[str] = Field(None, alias='alias_label')

    # A Blik-defined identifier for a specific Blik-enabled bank account that is associated with a given merchant. Used only in conjunction with a Consumer Reference.
    alias_key: typing.Optional[str] = Field(None, alias='alias_key')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
