# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.email import Email
from pay_pal_checkout_python_sdk.pydantic.merchant_partner_customer_id import MerchantPartnerCustomerId
from pay_pal_checkout_python_sdk.pydantic.phone_with_type import PhoneWithType

class Customer(BaseModel):
    id: typing.Optional[MerchantPartnerCustomerId] = Field(None, alias='id')

    email_address: typing.Optional[Email] = Field(None, alias='email_address')

    phone: typing.Optional[PhoneWithType] = Field(None, alias='phone')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
