# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.error_location import ErrorLocation

class ErrorDetails(BaseModel):
    # The unique, fine-grained application-level error code.
    issue: str = Field(alias='issue')

    # The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value.
    description: typing.Optional[str] = Field(None, alias='description')

    # The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors.
    field: typing.Optional[str] = Field(None, alias='field')

    # The value of the field that caused the error.
    value: typing.Optional[str] = Field(None, alias='value')

    location: typing.Optional[ErrorLocation] = Field(None, alias='location')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
