# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.language import Language

class ExperienceContextBase(BaseModel):
    # The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode.
    brand_name: typing.Optional[str] = Field(None, alias='brand_name')

    locale: typing.Optional[Language] = Field(None, alias='locale')

    # The location from which the shipping address is derived.
    shipping_preference: typing.Optional[Literal["GET_FROM_FILE", "NO_SHIPPING", "SET_PROVIDED_ADDRESS"]] = Field(None, alias='shipping_preference')

    # Describes the URL.
    return_url: typing.Optional[str] = Field(None, alias='return_url')

    # Describes the URL.
    cancel_url: typing.Optional[str] = Field(None, alias='cancel_url')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
