# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.money import Money

class Item(BaseModel):
    # The item name or title.
    name: str = Field(alias='name')

    unit_amount: Money = Field(alias='unit_amount')

    # The item quantity. Must be a whole number.
    quantity: str = Field(alias='quantity')

    # The detailed item description.
    description: typing.Optional[str] = Field(None, alias='description')

    tax: typing.Optional[Money] = Field(None, alias='tax')

    # The stock keeping unit (SKU) for the item.
    sku: typing.Optional[str] = Field(None, alias='sku')

    # The item category type.
    category: typing.Optional[Literal["DIGITAL_GOODS", "PHYSICAL_GOODS", "DONATION"]] = Field(None, alias='category')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
