# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.activity_timestamps import ActivityTimestamps
from pay_pal_checkout_python_sdk.pydantic.checkout_payment_intent import CheckoutPaymentIntent
from pay_pal_checkout_python_sdk.pydantic.link_description import LinkDescription
from pay_pal_checkout_python_sdk.pydantic.order_status import OrderStatus
from pay_pal_checkout_python_sdk.pydantic.payer import Payer
from pay_pal_checkout_python_sdk.pydantic.payment_source_response import PaymentSourceResponse
from pay_pal_checkout_python_sdk.pydantic.processing_instruction import ProcessingInstruction
from pay_pal_checkout_python_sdk.pydantic.purchase_unit import PurchaseUnit

OrderAuthorizeResponse = typing.Union[ActivityTimestamps,typing.Union[bool, date, datetime, dict, float, int, list, str, None]]
OrderAuthorizeResponse = object
