# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.language import Language
from pay_pal_checkout_python_sdk.pydantic.payment_method import PaymentMethod
from pay_pal_checkout_python_sdk.pydantic.stored_payment_source import StoredPaymentSource

class OrderApplicationContext(BaseModel):
    # DEPRECATED. The label that overrides the business name in the PayPal account on the PayPal site. The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.brand_name`). Please specify this field in the `experience_context` object instead of the `application_context` object.
    brand_name: typing.Optional[str] = Field(None, alias='brand_name')

    locale: typing.Optional[Language] = Field(None, alias='locale')

    # WARNING: This property is deprecated
    # DEPRECATED. DEPRECATED. The type of landing page to show on the PayPal site for customer checkout.  The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.landing_page`). Please specify this field in the `experience_context` object instead of the `application_context` object.
    landing_page: typing.Optional[Literal["LOGIN", "BILLING", "NO_PREFERENCE"]] = Field(None, alias='landing_page')

    # WARNING: This property is deprecated
    # DEPRECATED. DEPRECATED. The shipping preference:<ul><li>Displays the shipping address to the customer.</li><li>Enables the customer to choose an address on the PayPal site.</li><li>Restricts the customer from changing the address during the payment-approval process.</li></ul>.  The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.shipping_preference`). Please specify this field in the `experience_context` object instead of the `application_context` object.
    shipping_preference: typing.Optional[Literal["GET_FROM_FILE", "NO_SHIPPING", "SET_PROVIDED_ADDRESS"]] = Field(None, alias='shipping_preference')

    # DEPRECATED. Configures a <strong>Continue</strong> or <strong>Pay Now</strong> checkout flow.  The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.user_action`). Please specify this field in the `experience_context` object instead of the `application_context` object.
    user_action: typing.Optional[Literal["CONTINUE", "PAY_NOW"]] = Field(None, alias='user_action')

    payment_method: typing.Optional[PaymentMethod] = Field(None, alias='payment_method')

    # DEPRECATED. The URL where the customer is redirected after the customer approves the payment. The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.return_url`). Please specify this field in the `experience_context` object instead of the `application_context` object.
    return_url: typing.Optional[str] = Field(None, alias='return_url')

    # DEPRECATED. The URL where the customer is redirected after the customer cancels the payment. The fields in `application_context` are now available in the `experience_context` object under the `payment_source` which supports them (eg. `payment_source.paypal.experience_context.cancel_url`). Please specify this field in the `experience_context` object instead of the `application_context` object.
    cancel_url: typing.Optional[str] = Field(None, alias='cancel_url')

    stored_payment_source: typing.Optional[StoredPaymentSource] = Field(None, alias='stored_payment_source')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
