# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.address_portable2 import AddressPortable2
from pay_pal_checkout_python_sdk.pydantic.billing_agreement_id import BillingAgreementId
from pay_pal_checkout_python_sdk.pydantic.date_no_time import DateNoTime
from pay_pal_checkout_python_sdk.pydantic.email import Email
from pay_pal_checkout_python_sdk.pydantic.name2 import Name2
from pay_pal_checkout_python_sdk.pydantic.paypal_wallet_attributes import PaypalWalletAttributes
from pay_pal_checkout_python_sdk.pydantic.paypal_wallet_experience_context import PaypalWalletExperienceContext
from pay_pal_checkout_python_sdk.pydantic.phone_with_type import PhoneWithType
from pay_pal_checkout_python_sdk.pydantic.tax_info import TaxInfo
from pay_pal_checkout_python_sdk.pydantic.vault_id import VaultId

class PaypalWallet(BaseModel):
    vault_id: typing.Optional[VaultId] = Field(None, alias='vault_id')

    email_address: typing.Optional[Email] = Field(None, alias='email_address')

    name: typing.Optional[Name2] = Field(None, alias='name')

    phone: typing.Optional[PhoneWithType] = Field(None, alias='phone')

    birth_date: typing.Optional[DateNoTime] = Field(None, alias='birth_date')

    tax_info: typing.Optional[TaxInfo] = Field(None, alias='tax_info')

    address: typing.Optional[AddressPortable2] = Field(None, alias='address')

    attributes: typing.Optional[PaypalWalletAttributes] = Field(None, alias='attributes')

    experience_context: typing.Optional[PaypalWalletExperienceContext] = Field(None, alias='experience_context')

    billing_agreement_id: typing.Optional[BillingAgreementId] = Field(None, alias='billing_agreement_id')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
