# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.cobranded_card import CobrandedCard
from pay_pal_checkout_python_sdk.pydantic.paypal_wallet_vault_response import PaypalWalletVaultResponse

class PaypalWalletAttributesResponse(BaseModel):
    vault: typing.Optional[PaypalWalletVaultResponse] = Field(None, alias='vault')

    # An array of merchant cobranded cards used by buyer to complete an order. This array will be present if a merchant has onboarded their cobranded card with PayPal and provided corresponding label(s).
    cobranded_cards: typing.Optional[typing.List[CobrandedCard]] = Field(None, alias='cobranded_cards')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
