# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.phone import Phone
from pay_pal_checkout_python_sdk.pydantic.phone_type import PhoneType

class PhoneWithType(BaseModel):
    phone_number: Phone = Field(alias='phone_number')

    phone_type: typing.Optional[PhoneType] = Field(None, alias='phone_type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
