# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from pay_pal_checkout_python_sdk.pydantic.email import Email
from pay_pal_checkout_python_sdk.pydantic.vault_id import VaultId
from pay_pal_checkout_python_sdk.pydantic.venmo_wallet_attributes import VenmoWalletAttributes
from pay_pal_checkout_python_sdk.pydantic.venmo_wallet_experience_context import VenmoWalletExperienceContext

class VenmoWalletRequest(BaseModel):
    vault_id: typing.Optional[VaultId] = Field(None, alias='vault_id')

    email_address: typing.Optional[Email] = Field(None, alias='email_address')

    experience_context: typing.Optional[VenmoWalletExperienceContext] = Field(None, alias='experience_context')

    attributes: typing.Optional[VenmoWalletAttributes] = Field(None, alias='attributes')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
