# coding: utf-8

"""
    Orders

    An order represents a payment between two or more parties. Use the Orders API to create, update, retrieve, authorize, and capture orders.

    The version of the OpenAPI document: 2.13
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from pay_pal_checkout_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from pay_pal_checkout_python_sdk.api_response import AsyncGeneratorResponse
from pay_pal_checkout_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from pay_pal_checkout_python_sdk import schemas  # noqa: F401

from pay_pal_checkout_python_sdk.model.error500 import Error500 as Error500Schema
from pay_pal_checkout_python_sdk.model.patch_request import PatchRequest as PatchRequestSchema
from pay_pal_checkout_python_sdk.model.trackers_update_tracking_info_response import TrackersUpdateTrackingInfoResponse as TrackersUpdateTrackingInfoResponseSchema
from pay_pal_checkout_python_sdk.model.trackers_update_tracking_info403_response import TrackersUpdateTrackingInfo403Response as TrackersUpdateTrackingInfo403ResponseSchema
from pay_pal_checkout_python_sdk.model.error_default import ErrorDefault as ErrorDefaultSchema
from pay_pal_checkout_python_sdk.model.trackers_update_tracking_info404_response import TrackersUpdateTrackingInfo404Response as TrackersUpdateTrackingInfo404ResponseSchema
from pay_pal_checkout_python_sdk.model.trackers_update_tracking_info422_response import TrackersUpdateTrackingInfo422Response as TrackersUpdateTrackingInfo422ResponseSchema

from pay_pal_checkout_python_sdk.type.trackers_update_tracking_info_response import TrackersUpdateTrackingInfoResponse
from pay_pal_checkout_python_sdk.type.trackers_update_tracking_info403_response import TrackersUpdateTrackingInfo403Response
from pay_pal_checkout_python_sdk.type.patch_request import PatchRequest
from pay_pal_checkout_python_sdk.type.trackers_update_tracking_info422_response import TrackersUpdateTrackingInfo422Response
from pay_pal_checkout_python_sdk.type.error_default import ErrorDefault
from pay_pal_checkout_python_sdk.type.error500 import Error500
from pay_pal_checkout_python_sdk.type.trackers_update_tracking_info404_response import TrackersUpdateTrackingInfo404Response

from ...api_client import Dictionary
from pay_pal_checkout_python_sdk.pydantic.trackers_update_tracking_info_response import TrackersUpdateTrackingInfoResponse as TrackersUpdateTrackingInfoResponsePydantic
from pay_pal_checkout_python_sdk.pydantic.trackers_update_tracking_info422_response import TrackersUpdateTrackingInfo422Response as TrackersUpdateTrackingInfo422ResponsePydantic
from pay_pal_checkout_python_sdk.pydantic.patch_request import PatchRequest as PatchRequestPydantic
from pay_pal_checkout_python_sdk.pydantic.error_default import ErrorDefault as ErrorDefaultPydantic
from pay_pal_checkout_python_sdk.pydantic.error500 import Error500 as Error500Pydantic
from pay_pal_checkout_python_sdk.pydantic.trackers_update_tracking_info403_response import TrackersUpdateTrackingInfo403Response as TrackersUpdateTrackingInfo403ResponsePydantic
from pay_pal_checkout_python_sdk.pydantic.trackers_update_tracking_info404_response import TrackersUpdateTrackingInfo404Response as TrackersUpdateTrackingInfo404ResponsePydantic

# Path params


class IdSchema(
    schemas.StrSchema
):
    pass


class TrackerIdSchema(
    schemas.StrSchema
):
    pass
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'id': typing.Union[IdSchema, str, ],
        'tracker_id': typing.Union[TrackerIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_id = api_client.PathParameter(
    name="id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=IdSchema,
    required=True,
)
request_path_tracker_id = api_client.PathParameter(
    name="tracker_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=TrackerIdSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = PatchRequestSchema


request_body_patch_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor204(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor204Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_204 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor204,
    response_cls_async=ApiResponseFor204Async,
)
SchemaFor400ResponseBodyApplicationJson = TrackersUpdateTrackingInfoResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: TrackersUpdateTrackingInfoResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: TrackersUpdateTrackingInfoResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = TrackersUpdateTrackingInfo403ResponseSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: TrackersUpdateTrackingInfo403Response


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: TrackersUpdateTrackingInfo403Response


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = TrackersUpdateTrackingInfo404ResponseSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: TrackersUpdateTrackingInfo404Response


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: TrackersUpdateTrackingInfo404Response


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
SchemaFor422ResponseBodyApplicationJson = TrackersUpdateTrackingInfo422ResponseSchema


@dataclass
class ApiResponseFor422(api_client.ApiResponse):
    body: TrackersUpdateTrackingInfo422Response


@dataclass
class ApiResponseFor422Async(api_client.AsyncApiResponse):
    body: TrackersUpdateTrackingInfo422Response


_response_for_422 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor422,
    response_cls_async=ApiResponseFor422Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor422ResponseBodyApplicationJson),
    },
)
SchemaFor500ResponseBodyApplicationJson = Error500Schema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: Error500


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: Error500


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = ErrorDefaultSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: ErrorDefault


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: ErrorDefault


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _update_tracking_info_mapped_args(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        args.body = body if body is not None else _body
        if id is not None:
            _path_params["id"] = id
        if tracker_id is not None:
            _path_params["tracker_id"] = tracker_id
        args.path = _path_params
        return args

    async def _aupdate_tracking_info_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor204Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Update or cancel tracking information for a PayPal order
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_id,
            request_path_tracker_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'patch'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/checkout/orders/{id}/trackers/{tracker_id}',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_patch_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _update_tracking_info_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor204,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Update or cancel tracking information for a PayPal order
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_id,
            request_path_tracker_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'patch'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/v2/checkout/orders/{id}/trackers/{tracker_id}',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_patch_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class UpdateTrackingInfoRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aupdate_tracking_info(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor204Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_tracking_info_mapped_args(
            body=body,
            id=id,
            tracker_id=tracker_id,
        )
        return await self._aupdate_tracking_info_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def update_tracking_info(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
    ) -> typing.Union[
        ApiResponseFor204,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_tracking_info_mapped_args(
            body=body,
            id=id,
            tracker_id=tracker_id,
        )
        return self._update_tracking_info_oapg(
            body=args.body,
            path_params=args.path,
        )

class UpdateTrackingInfo(BaseApi):

    async def aupdate_tracking_info(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
        validate: bool = False,
        **kwargs,
    ) -> None:
        raw_response = await self.raw.aupdate_tracking_info(
            body=body,
            id=id,
            tracker_id=tracker_id,
            **kwargs,
        )
    
    
    def update_tracking_info(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
        validate: bool = False,
    ) -> None:
        raw_response = self.raw.update_tracking_info(
            body=body,
            id=id,
            tracker_id=tracker_id,
        )


class ApiForpatch(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apatch(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor204Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._update_tracking_info_mapped_args(
            body=body,
            id=id,
            tracker_id=tracker_id,
        )
        return await self._aupdate_tracking_info_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def patch(
        self,
        id: str,
        tracker_id: str,
        body: typing.Optional[PatchRequest] = None,
    ) -> typing.Union[
        ApiResponseFor204,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._update_tracking_info_mapped_args(
            body=body,
            id=id,
            tracker_id=tracker_id,
        )
        return self._update_tracking_info_oapg(
            body=args.body,
            path_params=args.path,
        )

